spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

server:
  port: 8080
  servlet:
    context-path: /y_lab_uni

logging:
  level:
    root: INFO